name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 27.1
          - snapshot

    steps:
    - uses: actions/checkout@v1

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: test
      run: sudo ./scripts/test-startup.sh
   