name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        emacs-version:
          - 27.1
          - snapshot

    steps:
    - uses: actions/checkout@v1

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: test
      run: 'mv -f ../.emacs.d ~/.emacs.d;
            emacs -nw --batch --eval \
            "(let ((debug-on-error (>=  emacs-major-version 26))
                   (url-show-status nil)
                   (user-emacs-directory default-directory)
                   (user-init-file (expand-file-name "~/build.el"))
                   (load-path (delq default-directory load-path)))
             (load-file user-init-file)
             (run-hooks (quote after-init-hook))
             (run-hooks (quote emacs-startup-hook)))"'
   